language: php

php:
  - 5.6
  - 7.0
#  - hhvm

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --prefer-source

notifications:
  email: false

script:
  phpunit tests/

cache:
  directories:
    $HOME/.composer/cache