language: php

php:
  - 5.6
  - 7.0
#  - hhvm

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --prefer-source

notifications:
  email: false

script:
  - php vendor/squizlabs/php_codesniffer/bin/phpcs rltam.php
  - phpunit tests/

