<?php
/**
 * Created by PhpStorm.
 * User: kimura
 * Date: 2016/11/27
 * Time: 13:52
 */
require_once dirname(__DIR__).DIRECTORY_SEPARATOR.'rltam.php';

class ConfigDataTest extends PHPUnit_Framework_TestCase
{
    
    public function setUp()
    {
        // parent::setUp(); // TODO: Change the autogenerated stub
        $this->config = new ConfigData();
    }
    
    public function tearDown()
    {
        // parent::tearDown(); // TODO: Change the autogenerated stub
        $this->config = null;
    }


    public function testEmpty()
    {
        $this->assertFalse($this->config->isEnabled());
    }
    
    public function testListMember()
    {
        $member = new Member();
        
        $this->assertCount(0, $this->config->getListMember());
        
        $this->config->addListMember($member);
        $this->config->addListMember($member);
        $this->config->addListMember($member);
        $this->config->addListMember($member);
        $this->config->addListMember($member);
        
        $this->assertCount(5, $this->config->getListMember());
        
    }
    
    public function testSkipData()
    {
        $member = new Member();
        
        $this->assertCount(0, $this->config->getArySkipData());
        
        $this->config->addArySkipData($member);
        $this->config->addArySkipData($member);
        $this->config->addArySkipData($member);
        $this->config->addArySkipData($member);
        $this->config->addArySkipData($member);
        
        $this->assertCount(5, $this->config->getArySkipData());
        
    }
    
    
}