<?php
/**
 * Created by PhpStorm.
 * User: kimura
 * Date: 2016/11/27
 * Time: 13:52
 */
require_once dirname(__DIR__).DIRECTORY_SEPARATOR.'rltam.php';

class ConfigDataTest extends PHPUnit_Framework_TestCase
{
    
    public function setUp()
    {
        // parent::setUp(); // TODO: Change the autogenerated stub
        $this->config = new ConfigData();
    }
    
    public function tearDown()
    {
        // parent::tearDown(); // TODO: Change the autogenerated stub
        $this->config = null;
    }


    public function testEmpty()
    {
        $this->assertFalse($this->config->isEnabled());
    }
    
    
}