<?php
/**
 * Created by PhpStorm.
 * User: kimura
 * Date: 2016/11/27
 * Time: 13:52
 */
require_once dirname(__DIR__) . DIRECTORY_SEPARATOR . 'rltam.php';

class MainFuncTest extends PHPUnit_Framework_TestCase
{
    
    public function setUp()
    {
        // parent::setUp(); // TODO: Change the autogenerated stub
    }
    
    public function tearDown()
    {
        // parent::tearDown(); // TODO: Change the autogenerated stub
    }
    
    
    /**
     * @runInSparateProcess
     * @preserveGlobalState
     */
    public function testDefine()
    {
        // $this->assertFalse($this->member->isEnabled());
        $this->assertEquals(0, constant('ARGV_INDEX_PHP_FNAME'));
        $this->assertEquals(1, constant('ARGV_INDEX_CONF_FNAME'));
        $this->assertEquals(2, constant('ARGV_INDEX_SMTP_SERVER'));
        $this->assertEquals(3, constant('ARGV_INDEX_SMTP_PORT_NO'));
        $this->assertEquals(4, constant('ARGV_INDEX_MAX'));
        
        $this->assertStringMatchesFormat("%s@%s", constant('MAIL_FROM'));
        
        $this->assertStringMatchesFormat("%s", constant('OS_ENC'));
        
    }
    
}